import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const mainMenu = readFileSync('src/game/phaser/scenes/MainMenuScene.js', 'utf8');
const reset = readFileSync('src/ui/MissionShellReset.js', 'utf8');
const index = readFileSync('index.html', 'utf8');
const renderer = readFileSync('src/game/three/ThreeMissionWorldRenderer.js', 'utf8');
assert.match(mainMenu, /stopMissionScenesForMainMenu/);
const stopMethod = mainMenu.match(/stopMissionScenesForMainMenu\(\) \{[\s\S]*?\n  \}/)?.[0] ?? '';
assert.match(stopMethod, /sceneManager\.stop\?\.\(key\)/);
assert.doesNotMatch(stopMethod, /\.shutdown\?\.\(/);
assert.match(reset, /ANCHOR_SCENE_ISOLATION_DEBUG/);
assert.match(reset, /threeMissionCanvasCount/);
assert.match(reset, /planningCleanupInvocationCount/);
assert.match(reset, /activeWaterColumnSlabCount/);
assert.equal(index.includes('src/app/main.js'), false);
assert.equal(index.includes('AnchorBrowserRuntime'), false);
assert.match(renderer, /disposeThreeGpuTimer/, 'renderer teardown disposes optional GPU timer diagnostics');
assert.match(renderer, /disposeThreeInstancedCurrentGlyphLayer/, 'renderer teardown disposes FLOW-R2A instanced current glyph resources');
assert.match(renderer, /currentGlyphFrustumSummary/, 'renderer publishes bounded current glyph frustum diagnostics');
const nextHost = readFileSync('src/app/production/AnchorProductionViewHost.js', 'utf8');
assert.match(nextHost, /disposeActiveView/, 'R3A next shell has route-scoped disposal');
assert.match(nextHost, /clearRouteRegions/, 'R3A next shell clears route-owned regions on transition');
console.log('audit_three_scene_isolation passed');
