import assert from 'node:assert/strict';
import { buildFlowR2A5CurrentDynamicsMetrics } from './flow_r2a5_current_dynamics_helpers.mjs';
import { buildGliderRenderPhysicsParityProbe } from './flow_runtime_r1_current_helpers.mjs';
const m = buildFlowR2A5CurrentDynamicsMetrics();
const parity = buildGliderRenderPhysicsParityProbe({ seed: 'flow-runtime-r1-display-physics-audit' });
assert.equal(m.displayModeDigestCount, 1, 'display modes do not mutate field digest');
assert.equal(m.displayModeCurrentSampleCount, 1, 'display modes do not mutate sampled current');
assert.ok(parity.appliedSampleDelta <= 1e-9, 'physics-applied current remains canonical and independent of display visibility');
assert.equal(parity.displayChangesPhysics, false, 'display settings do not change current physics');
console.log('[audit_current_display_physics_invariance] PASS', { appliedSampleDelta: parity.appliedSampleDelta });