import fs from 'node:fs';
import assert from 'node:assert/strict';

const scene = fs.readFileSync('src/game/phaser/scenes/BathymetryWorldViewScene.js', 'utf8');
const viewModel = fs.readFileSync('src/core/rendering/BathymetryWorldRenderViewModel.js', 'utf8');
const missionRenderer = fs.readFileSync('src/game/three/ThreeMissionWorldRenderer.js', 'utf8');
const missionScene = fs.readFileSync('src/game/phaser/scenes/MissionWorkspaceScene.js', 'utf8');

assert.match(scene, /plannedWaypoints:\s*this\.plan\.waypoints/, 'Bathymetry demo passes local fixture waypoints into its view model');
assert.match(scene, /depthMeters:\s*35/, 'Bathymetry demo fixture supplies explicit thermocline depths');
assert.match(scene, /depthMeters:\s*120/, 'Bathymetry demo fixture supplies explicit deep depths');
assert.doesNotMatch(scene, /DiveProfileModel|GliderDiveStateMachine|PlannedDiveSegmentViewModel/, 'Bathymetry demo route is not generated by canonical dive prediction');
assert.match(viewModel, /plan\?\.plannedWaypoints \?\? plan\?\.waypoints/, 'Bathymetry view model consumes supplied waypoint geometry');
assert.match(viewModel, /flowOverlaySummary.*not ocean current/s, 'Bathymetry demo classifies flow overlay as illustrative diagnostics');
assert.doesNotMatch(missionRenderer, /BathymetryWorldViewScene/, 'Production mission renderer must not depend on demo scene fixture state');
assert.doesNotMatch(missionScene, /BathymetryWorldViewScene/, 'Mission workspace must not import bathymetry demo scene');
console.log(JSON.stringify({
  ok: true,
  routeSource: 'fixtureExplicitDepthWaypoints',
  canonicalDiveModelUsed: false,
  productionDependsOnDemoFixture: false,
  reusableComponents: ['ThreeBathymetryRenderer terrain/water conventions', 'BathymetryWorldRenderViewModel transforms', 'camera framing patterns']
}));