import assert from 'node:assert/strict';
import { runMissionSimulatorParityHarness } from './mission_simulator_parity_harness.mjs';
import * as pkg from '../../packages/mission-simulator/src/index.js';
import { stepAgentToward } from '../../src/core/sim/Physics.js';
import { updateSampling } from '../../src/core/sim/Sampling.js';
import { createAgent } from '../../src/core/sim/Agent.js';
import { advanceWaypointIfReached } from '../../src/core/planning/PlanExecutor.js';
import { createTerrainSimulationDiagnostics } from '../../src/core/simulation/TerrainSimulationDiagnostics.js';

assert.equal(stepAgentToward, pkg.stepAgentToward);
assert.equal(updateSampling, pkg.updateSampling);
assert.equal(createAgent, pkg.createAgent);
assert.equal(advanceWaypointIfReached, pkg.advanceWaypointIfReached);
assert.equal(createTerrainSimulationDiagnostics, pkg.createTerrainSimulationDiagnostics);
const record = runMissionSimulatorParityHarness();
assert.equal(record.comparisonStatus, 'PASS');
assert.equal(record.firstDivergence, null);
const input = pkg.createMissionSimulationInput({ agentConfigurations: [{ id: 'g1', start: { x: 0, y: 0 } }], plan: { agentPlans: [{ agentId: 'g1', waypoints: [{ id: 'w1', x: 1, y: 0 }] }] }, missionDurationSeconds: 3, timeStepSeconds: 1 });
const simulator = pkg.createMissionSimulator(input);
pkg.stepMissionSimulator(simulator, { type: 'step', dtSeconds: 1 });
const debug = pkg.missionSimulatorDebugSummary(simulator);
assert.equal(debug.engineId, 'packages/mission-simulator');
assert.equal(debug.packageOwnsPhysics, true);
assert.equal(debug.packageOwnsRouteProgress, true);
assert.equal(debug.packageOwnsEnvironmentSampling, true);
assert.equal(debug.packageOwnsTerminalEvaluation, true);
assert.equal(debug.packageOwnsRawMetrics, true);
assert.equal(debug.packageOwnsOfficialScoring, false);
assert.equal(debug.packageUsesThree, false);
assert.equal(debug.packageUsesPhaser, false);
assert.equal(debug.packageUsesDom, false);
assert.equal(debug.legacyProductionTransitionCount, 0);
assert.equal(debug.duplicateEngineCount, 0);
assert(debug.packageTransitionCount > 0);
console.log('smoke_mission_simulator_authoritative_runtime: ok', { resultDigest: record.packageKernel.resultDigest, productionResultDigest: record.productionAdapter.resultDigest });
