import assert from 'node:assert/strict';
import * as THREE from '../../node_modules/three/build/three.module.js';
import { createMissionWorldFixture } from './mission_world_fixture.mjs';
import { missionWorldRenderInputFromWorkspace } from '../../src/core/rendering/MissionWorldStateAdapter.js';
import { buildMissionWorldRenderViewModel } from '../../src/core/rendering/MissionWorldRenderViewModel.js';
import { updateThreeDropZoneLayer } from '../../src/game/three/layers/ThreeDropZoneLayer.js';
import { updateThreeGliderLayer } from '../../src/game/three/layers/ThreeGliderLayer.js';
import { updateThreeWaypointLayer } from '../../src/game/three/layers/ThreeWaypointLayer.js';
import { updateThreeRouteLayer } from '../../src/game/three/layers/ThreeRouteLayer.js';
import { updateThreePlanningMarkerLayer } from '../../src/game/three/layers/ThreePlanningMarkerLayer.js';
import { updateThreePriorityTargetLayer } from '../../src/game/three/layers/ThreePriorityTargetLayer.js';
import { updateThreeCurrentVectorLayer } from '../../src/game/three/layers/ThreeCurrentVectorLayer.js';
import { updateThreeHazardLayer, updateThreeConstraintLayer } from '../../src/game/three/layers/ThreeHazardLayer.js';
import { updateThreeSelectionLayer } from '../../src/game/three/layers/ThreeSelectionLayer.js';
import { clearGroup } from '../../src/game/three/layers/ThreeMissionLayerUtils.js';

const fixture = createMissionWorldFixture();
const viewModel = buildMissionWorldRenderViewModel(missionWorldRenderInputFromWorkspace({ app: { state: fixture.state } }));
const groups = Object.fromEntries(['drop', 'glider', 'waypoint', 'route', 'marker', 'star', 'current', 'hazard', 'constraint', 'selection'].map((key) => [key, new THREE.Group()]));
updateThreeDropZoneLayer(groups.drop, viewModel);
updateThreeGliderLayer(groups.glider, viewModel);
updateThreeWaypointLayer(groups.waypoint, viewModel);
updateThreeRouteLayer(groups.route, viewModel);
updateThreePlanningMarkerLayer(groups.marker, viewModel);
updateThreePriorityTargetLayer(groups.star, viewModel);
updateThreeCurrentVectorLayer(groups.current, viewModel);
updateThreeHazardLayer(groups.hazard, viewModel);
updateThreeConstraintLayer(groups.constraint, viewModel);
updateThreeSelectionLayer(groups.selection, viewModel);
assert.ok(groups.drop.children.length >= viewModel.dropZones.length, 'drop zones should render cells');
assert.equal(groups.glider.children.length, viewModel.gliders.length);
assert.equal(groups.waypoint.children.length, viewModel.waypoints.length);
assert.equal(groups.route.children.length, viewModel.routes.length);
assert.equal(groups.marker.children.length, viewModel.planningMarkers.length);
assert.equal(groups.star.children.length, viewModel.priorityTargets.length);
assert.ok(groups.current.children.length >= viewModel.vectorFieldLayer.vectors.length, 'current vectors should render line/head objects');
assert.equal(groups.hazard.children.length, viewModel.hazards.length);
assert.equal(groups.constraint.children.length, viewModel.constraints.length);
assert.ok(groups.glider.children.some((child) => child.userData.agentId === 'glider-alpha'));
assert.ok(groups.marker.children.every((child) => child.userData.executable === false));
for (const group of Object.values(groups)) clearGroup(group);
assert.ok(Object.values(groups).every((group) => group.children.length === 0));
console.log('Three mission entity layers smoke passed');

